In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
p_list = [1, 2, 3]
p_list

[1, 2, 3]

In [4]:
np_1d = np.array(p_list)

In [5]:
np_1d

array([1, 2, 3])

look for the type

In [6]:
type(p_list)

list

In [7]:
type(np_1d)

numpy.ndarray

In [8]:
p_matrix = [[1,2,3],[4,5,6],[7,8,9]]
p_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np_matrix = np.array(p_matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Using built-in methods

In [10]:
np.arange(0, 10) # start, stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2) # start, stop, step

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3) # 1D

array([0., 0., 0.])

In [13]:
np.zeros((3, 5)) # 2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.linspace(0, 10, 50) # start, stop, number of elements

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random value generation

### one value from range 0..1

In [15]:
rng = np.random.default_rng()
rng.random()

0.1325774126698438

## uniform sequence
Return an array of the given shape with random samples from a uniform distribution

In [16]:
np.random.uniform(0, 1, 10) # (low, high, size)

array([0.09143457, 0.61633531, 0.46970408, 0.76033499, 0.2035084 ,
       0.147414  , 0.3525883 , 0.87185168, 0.05733833, 0.04701562])

### randn
Return samples from the “standard normal” distribution.

In [17]:
np.random.randn(2,2) # standard normal (Gaussian) distribution of mean 0 and variance 1

array([[-1.00705205, -0.09563147],
       [-2.01477949, -0.76670332]])

### normal

In [18]:
mu, sigma = 1, 0.5 # mean and standard deviation
np.random.normal(mu, sigma, size = (3, 2))

array([[1.09156466, 0.70018696],
       [1.53635316, 1.32496124],
       [1.14143837, 1.7447893 ]])

### multivariate normal

In [19]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[ 1.76980509,  2.49071912],
        [ 0.90626021,  2.36108164]],

       [[ 0.23694921,  1.72208858],
        [-0.57323012,  1.11781907]],

       [[ 0.73169074,  2.45037097],
        [ 0.63494223,  3.50932252]]])

### randint
Return random integers

In [20]:
np.random.randint(1, 100, 5) # randint(low, high=None, size=None)

array([45, 54, 60, 15, 26])

### seed()
The seed() method is used to initialize the random number generator.

In [21]:
np.random.seed(0)

### Operations

In [22]:
a1d = np.arange(0, 10)
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a2d = a1d.reshape(2, 5) # https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape
a2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
xs = np.random.randint(1, 100, 10)
xs

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [25]:
xs.mean()

np.float64(53.5)

In [26]:
xs.max() # value

np.int64(88)

In [27]:
xs.argmax() # index

np.int64(9)

In [28]:
xs1 = np.array([1, 2, 3])
xs2 = np.array([4, 5, 6])

In [29]:
xs1 + xs2 # must have the same length

array([5, 7, 9])

In [30]:
xs1 * xs2 # must have the same length

array([ 4, 10, 18])

In [31]:
np.exp(xs1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [32]:
np.log(xs1)

array([0.        , 0.69314718, 1.09861229])